<!doctype html>
<html lang="en" class="scroll-smooth">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow">
  <title>{{TITLE}} | Free HTL Guide</title>
  <meta name="description" content="Premium learning preview of the {{TITLE}} HT/HTL exam-preparation experience.">
  <link rel="canonical" href="{{CANONICAL}}"><link rel="stylesheet" href="{{PREFIX}}assets/guide.css"><link rel="stylesheet" href="{{PREFIX}}assets/premium-preview.css"><meta name="theme-color" content="#0F4C81">
</head>
<body data-page="premium-preview" data-premium-ui-state="loading"><a class="skip" href="#main">Skip to content</a>
<header class="site-header"><div class="bar"><a class="brand" href="{{PREFIX}}index.html">Free HTL Guide</a><nav class="nav" aria-label="Primary"><a href="{{PREFIX}}index.html#modules">Course</a><a href="{{PREFIX}}practice.html">Practice</a><a href="{{PREFIX}}mock-exam.html">Mock exams</a><a href="{{PREFIX}}my-progress.html">My progress</a></nav><div class="actions"><button id="themeBtn" class="btn" type="button" aria-label="Toggle dark mode">🌙</button><button id="menuBtn" class="btn menu-btn" type="button" aria-expanded="false" aria-controls="mobileMenu">Menu</button><a class="btn" href="{{PREFIX}}account/sign-in.html">Sign in</a><a class="btn btn-primary" href="{{PREFIX}}account/sign-up.html">Create free account</a></div></div><nav id="mobileMenu" class="mobile-menu" aria-label="Mobile"><a href="{{PREFIX}}index.html#modules">Course</a><a href="{{PREFIX}}practice.html">Practice</a><a href="{{PREFIX}}mock-exam.html">Mock exams</a><a href="{{PREFIX}}my-progress.html">My progress</a><a href="{{PREFIX}}account/sign-in.html">Sign in</a><a href="{{PREFIX}}account/sign-up.html">Create free account</a></nav></header>
<main id="main" class="preview-shell"><section class="preview-hero"><div class="preview-copy"><p class="eyebrow">{{EYEBROW}}</p><h1>{{TITLE}}</h1><p class="lead">{{SUMMARY}}</p><div class="preview-actions"><a class="btn btn-primary" href="{{PREFIX}}modules/fixation-guide-v3.html">Start the free Fixation lesson</a><a class="btn" href="{{PREFIX}}pricing.html" data-premium-upgrade-action>Compare Premium plans</a><a class="btn" href="{{PREFIX}}premium/index.html" data-premium-account-action hidden>Open Premium library</a>{{PROOF_LINK}}</div><p class="small muted" data-premium-preview-context>Sign in to let this page confirm the access attached to your account.</p></div><aside class="card preview-card"><p class="eyebrow" data-premium-preview-label>Checking Premium access…</p><h2 data-premium-preview-message>Checking what your account can open</h2><ul class="preview-list">{{FEATURES}}</ul><p class="small muted" data-premium-preview-detail aria-live="polite">Your access is confirmed from trusted account records.</p></aside></section><section class="card preview-security-note"><h2>Secure Premium delivery</h2><p>Premium lesson and question content is delivered only after the server verifies an eligible account. Page wording and browser storage never grant access.</p><p><a class="btn" href="{{PREFIX}}index.html#modules">Explore the HT/HTL course</a></p></section></main>
<footer class="footer"><div class="footer-inner"><span>© <span data-year></span> Free HTL Guide</span><span><a href="{{PREFIX}}editorial.html">Editorial standards</a> · <a href="{{PREFIX}}privacy.html">Privacy</a> · <a href="{{PREFIX}}faq.html">FAQ</a></span></div></footer><script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.110.8" defer></script><script src="{{PREFIX}}assets/supabase-config.js" defer></script><script src="{{PREFIX}}assets/auth-service.js" defer></script><script src="{{PREFIX}}assets/billing-service.js" defer></script><script src="{{PREFIX}}assets/guide.js" defer></script><script src="{{PREFIX}}assets/premium-ui.js" defer></script></body></html>
